movie/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
     path('',views.index,name="index"),
     path('movie/<int:movie_id>/',views.detail,name='detail'),
     path('add/',views.add_movie,name='add_movie'),
     path('update/<int:id>/',views.update,name='update'),
     path('deletion/<int:id>/',views.deletion,name='deletion'),
]

movie/movieproject/movieproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                    document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

movie/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie/movieproject/movieapp/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movie/movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import MovieForm
from .models import Movie

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={'movie_list':movie}
    return render(request,"index.html",context)
    #return HttpResponse("Hello")

def detail(request,movie_id):
    #return  HttpResponse ("This movie no is %s" %movie_id)
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return  render(request,"add.html")

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return  redirect('/')
    return render(request,"edit.html",{'form':form,'movie':movie})

def deletion(request,id):
    if request.method == 'POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render (request,"delete.html")

movie/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body%}
<div style="background-color:#1940BB;">
<h3>Add movie</h3>
    </div>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
    <table>
        <tr>
            <th>Enter the movie name:   </th>
            <td><input type="text" name="name" placeholder="Enter the Movie name"></td>
        </tr>
   <tr>
            <th>Enter the movie desc:   </th>
            <td><input type="text" name="desc" placeholder="Enter the Movie desc"></td>
        </tr>
           <tr>
            <th>Enter the movie year:   </th>
            <td><input type="text" name="year" placeholder="Enter the Movie year"></td>
        </tr>
           <tr>
            <th>Upload the movie image:   </th>
            <td><input type="FILE" name="img" ></td>
        </tr>


    </table>

    <a href="index.html" ><input type="submit" style="background-color:#119830;"></a>

    </form>
{% endblock %}

movie/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color:#207683;">
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie Project
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie/movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <div class="row" >

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Are you sure to delete?
    <input type="submit">
</form>
    </div>
</div>

{% endblock %}

movie/movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <div class="row" >
        <div class="col-md-6">
           <img src={{movie.img.url}} width="350" height="350">
        </div>
           <div class="col-md-6">
               <h2>{{ movie.name}}</h2>
           <h5 style="text-align: left;"><i>  {{movie.desc}}
            {{movie.year}} </i></h5>
               <br><br><br>
             <a class="btn btn-warning" href ="{% url 'movieapp:update' movie.id %}">Update</a>
             <a class="btn btn-danger" href ="{% url 'movieapp:deletion' movie.id %}">Delete</a>
        </div>

    </div>
</div>

{% endblock %}

movie/movieproject/templates/edit.html
{% extends 'base.html'%}
{% block body%}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<input type="submit">
     </form>
{% endblock %}

movie/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <div class="row">
        {% for i in movie_list%}
        <div class="col-md-3">
            <div class="card" >
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px"  height="200px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Submit</a>
  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}